plugins {
    id 'java'
    id 'jacoco'
}

group = 'ru.nsu.a.maslova1.dsl'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

jacocoTestReport {
    reports {
        xml.required = true
    }
}

dependencies {
    // Удалите старую зависимость и добавьте актуальную
    implementation 'org.apache.groovy:groovy:4.0.25'
    implementation 'org.apache.groovy:groovy-json:4.0.25'
    // Если вам нужны другие модули Groovy, добавляйте их по аналогии
}