@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "ru.nsu.a.maslova1.pizzeria.Pizzeria",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_109392 { 
   	label=nsu
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_105127235 { 
   	label=a
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Client1767622510[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Client</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   orderCounter: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   orderQueue: OrderQueue [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   running: boolean [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ run()</TD></TR>
<TR><TD ALIGN="LEFT" >+ shutdown()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Order1771334349[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Order</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   status: OrderStatus [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

OrderQueue1771334349[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)OrderQueue</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   queue: Queue&lt;Order&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addOrder(order: Order)</TD></TR>
<TR><TD ALIGN="LEFT" >+ size(): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Pizzeria1329743726[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Pizzeria</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   bakers: List&lt;Thread&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   client: Client [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   couriers: List&lt;Thread&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   file: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   input: ReadFile [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   orderQueue: OrderQueue [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   warehouse: Warehouse [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   workTime: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- finishAllOrders()</TD></TR>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
<TR><TD ALIGN="LEFT" >- shutdown()</TD></TR>
<TR><TD ALIGN="LEFT" >+ start()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ReadFile1767622510[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ReadFile</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   bakers: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   bakersSpeed: int[] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   couriers: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   timer: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   trunkCapacity: int[] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   warehouseCapacity: int [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Warehouse1665967841[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Warehouse</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   capacity: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   storage: Queue&lt;Order&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ put(order: Order)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Client1767622510 -> OrderQueue1771334349[label="orderQueue
[0..1]"];
Pizzeria1329743726 -> Client1767622510[label="client
[0..1]"];
Pizzeria1329743726 -> OrderQueue1771334349[label="orderQueue
[0..1]"];
Pizzeria1329743726 -> ReadFile1767622510[label="input
[0..1]"];
Pizzeria1329743726 -> Warehouse1665967841[label="warehouse
[0..1]"];
Warehouse1665967841 -> Order1771334349[label="storage
[0..*]"];
    
}
@enduml